@SecurityJWTDemo_HostAddress = http://localhost:5000

GET {{SecurityJWTDemo_HostAddress}}/customer
Accept: application/json
Authorization: Bearer token

###

POST {{SecurityJWTDemo_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "prajakta",
  "password": "123"
}

###
POST http://localhost:5028/api/v1/auth/login
Content-Type: application/json

{
  "username": "sarah",
  "password": "s@123"
}

### LOGIN
POST http://localhost:5028/api/v1/Auth/login
Content-Type: application/json

{
  "username": "sarah",
  "password": "s@123"
}

###

### GET CUSTOMER
GET http://localhost:5028/api/v1/Customer
Authorization: Bearer "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2FyYWgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImFnZSI6IjI1IiwiZXhwIjoxNzcyNzkyNzMwLCJpc3MiOiJyZXZhdHVyZSIsImF1ZCI6ImRvdG5ldC1iYXRjaC0yMDI2In0.zucQVqdZ0mO5_Z-sydZoey7uB5sWMcdM2tG5IbFTPTw"